quick exit if there is no git

diff --git a/git-travel b/git-travel
--- a/git-travel
+++ b/git-travel
@@ -37,7 +37,7 @@ check_worktree() {
         echo "Working tree contains uncommited changes
 git-travel requires clean working tree.
 Please commit, stash, or discard local changes."
-        exit 1
+        exit 3
     fi
 }
 
@@ -194,6 +194,11 @@ travel_non_linux() {
 
     "$fn"
 }
+
+if ! command -v git >> /dev/null 2>&1; then
+    echo "Git is not found, please ensure that git is installed and available in PATH"
+    exit 1
+fi
 
 if uname -a | grep Linux >> /dev/null 2>&1; then
     travel_linux "$@"
