print usage and error messages to stderr

diff --git a/git-travel b/git-travel
--- a/git-travel
+++ b/git-travel
@@ -15,7 +15,7 @@ OPTIONS
 \t-f, --forward\tCheckout to N-th commit forward from current commit in history of the branch.\n
 \t-n <N>\t\tSet the number of commits for go forward or backward. N equals 1 if not specified.\n
 \t-H, --head\tCheckout to HEAD of the branch - latest commit.\n
-\t-T, --tail\tCheckout to first commit of the branch.\n"
+\t-T, --tail\tCheckout to first commit of the branch.\n" >&2
     exit 2
 }
 
@@ -28,7 +28,7 @@ OPTIONS
 \t-f\tCheckout to N-th commit forward from current commit in history of the branch.\n
 \t-n <N>\tSet the number of commits for go forward or backward. N equals 1 if not specified.\n
 \t-H\tCheckout to HEAD of the branch - latest commit.\n
-\t-T\tCheckout to first commit of the branch.\n"
+\t-T\tCheckout to first commit of the branch.\n" >&2
     exit 2
 }
 
@@ -36,7 +36,7 @@ check_worktree() {
     if ! git status | grep 'working tree clean' >> /dev/null; then
         echo "Working tree contains uncommited changes
 git-travel requires clean working tree.
-Please commit, stash, or discard local changes."
+Please commit, stash, or discard local changes." >&2
         exit 3
     fi
 }
@@ -105,7 +105,7 @@ validate_branch () {
 travel_linux() {
     usage=usage_linux
     if [ "$#" -lt 1 ]; then
-        echo "Illegal number of parameters"
+        echo "Illegal number of parameters" >&2
         "$usage"
     fi
 
@@ -126,9 +126,9 @@ travel_linux() {
                 "$usage";;
             -n)
                 if [ "$2" -ge 0 ] >> /dev/null 2>&1; then
-                    N=$2;
+                    N=$2
                 else
-                    echo "-n takes an positive integer as a value"
+                    echo "-n takes an positive integer as a value" >&2
                     "$usage"
                 fi
                 shift 2;;
@@ -148,7 +148,7 @@ travel_linux() {
                 shift;
                 break;;
             *)
-                echo "Unexpected option: $1";
+                echo "Unexpected option: $1" >&2;
                 "$usage" ;;
         esac
     done
@@ -159,7 +159,7 @@ travel_linux() {
 travel_non_linux() {
     usage=usage_non_linux
     if [ "$#" -lt 1 ]; then
-        echo "Illegal number of parameters"
+        echo "Illegal number of parameters" >&2
         "$usage"
     fi
 
@@ -173,9 +173,9 @@ travel_non_linux() {
                 "$usage";;
             n)
                 if [ "$OPTARG" -ge 0 ] >> /dev/null 2>&1; then
-                    N=$OPTARG;
+                    N=$OPTARG
                 else
-                    echo "-n takes an positive integer as a value"
+                    echo "-n takes an positive integer as a value" >&2
                     "$usage"
                 fi;;
             b)
@@ -187,7 +187,7 @@ travel_non_linux() {
             T)
                 fn="go_tail";;
             *)
-                echo "Unexpected option: $flag";
+                echo "Unexpected option: $flag" >&2;
                 "$usage" ;;
         esac
     done
@@ -196,7 +196,7 @@ travel_non_linux() {
 }
 
 if ! command -v git >> /dev/null 2>&1; then
-    echo "Git is not found, please ensure that git is installed and available in PATH"
+    echo "Git is not found, please ensure that git is installed and available in PATH" >&2
     exit 1
 fi
 
